#!/bin/bash
# Simpel Change Root For Linux ( ALL LINUX OS )
# Author = Wiliam
# Telegram = t.me/user_legend
# ================================================

# Clear
clear
rm -f root.sh

# update & upgrade repository
apt update && apt upgrade -y
clear

# Get Passwd
read -p "Please Input an New Password For Root : " Pass

# Starting Changes To Root
rm -f /etc/ssh/sshd_config
wget -O /etc/ssh/sshd_config https://raw.githubusercontent.com/osjekwknwjsk/root/main/sshd
echo -e "$Pass\n$Pass\n"|passwd root &> /dev/null
IPANDA=$(wget -qO- ifconfig.co);

# Successful
clear
echo "AUTHOR = WILL I AM"
echo "Please Save This VPS Account Information"
echo "============================================"
echo "  IP ADDRESS = $IPANDA"
echo "  Username   = root"
echo "  Password   = $Pass"
echo "============================================"
echo ""
echo "VPS Will Rebooting On 10 Second !!!!!"

rm -f root.sh
sleep 10
reboot
